# ***K folds Cross Validation***

## ***Import the Libraries***

In [0]:
import pandas as pd
import numpy as np

In [0]:
from google.colab import files
uploaded = files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads.csv


## ***Import the dataset***

In [0]:
import io

ads = pd.read_csv(io.StringIO(uploaded['Social_Network_Ads.csv'].decode('utf-8')))
ads.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [0]:
ads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null float64
EstimatedSalary    400 non-null float64
Purchased          400 non-null int64
dtypes: float64(2), int64(2), object(1)
memory usage: 15.7+ KB


In [0]:
ads.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [0]:
del ads['User ID']
ads.head()

Gender   Age  EstimatedSalary  Purchased
0    Male  19.0          19000.0          0
1    Male  35.0          20000.0          0
2  Female  26.0          43000.0          0
3  Female  27.0          57000.0          0
4    Male  19.0          76000.0          0

In [0]:
x=ads.iloc[:,:-1]
y=ads.iloc[:,3]

In [0]:
x.head()

Gender   Age  EstimatedSalary
0    Male  19.0          19000.0
1    Male  35.0          20000.0
2  Female  26.0          43000.0
3  Female  27.0          57000.0
4    Male  19.0          76000.0

In [0]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

## ***Preporocessing***

In [0]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
x.iloc[:,0]=labelencoder.fit_transform(x.iloc[:,0])

In [0]:
x.head()

Gender   Age  EstimatedSalary
0       1  19.0          19000.0
1       1  35.0          20000.0
2       0  26.0          43000.0
3       0  27.0          57000.0
4       1  19.0          76000.0

In [0]:
x['Age'].unique()

array([19., 35., 26., 27., 32., 25., 20., 18., 29., 47., 45., 46., 48.,
       49., 31., 21., 28., 33., 30., 23., 24., 22., 59., 34., 39., 38.,
       37., 42., 40., 36., 41., 58., 55., 52., 60., 56., 53., 50., 51.,
       57., 44., 43., 54.])

In [0]:
x.head()

Gender   Age  EstimatedSalary
0       1  19.0          19000.0
1       1  35.0          20000.0
2       0  26.0          43000.0
3       0  27.0          57000.0
4       1  19.0          76000.0

In [0]:
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("norm1", StandardScaler(), [2])])
x['EstimatedSalary']=ct.fit_transform(x) 

In [0]:
x1=pd.DataFrame(x)
x1.head()

Gender   Age  EstimatedSalary
0       1  19.0        -1.490046
1       1  35.0        -1.460681
2       0  26.0        -0.785290
3       0  27.0        -0.374182
4       1  19.0         0.183751

## ***Splitting the Dataset and Training with KNN***

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state =5)
knnclassifier = KNeighborsClassifier(n_neighbors=5)
knnclassifier.fit(x_train,y_train)
y_pred = knnclassifier.predict(x_test)
metrics.accuracy_score(y_test,y_pred)

0.91

## ***Cross Validation***

In [0]:
from sklearn.model_selection import cross_val_score
knnclassifier = KNeighborsClassifier(n_neighbors=5)
cross_val=cross_val_score(knnclassifier, x, y, cv=10, scoring ='accuracy')

In [0]:
cross_val

array([0.95121951, 0.70731707, 0.87804878, 0.95      , 0.95      ,
       0.9       , 0.85      , 0.76923077, 0.82051282, 0.94871795])

In [0]:
cross_val.mean()

0.8725046904315196

In [0]:
cross_val.std()

0.08121842538641982

In [0]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
regressor = DecisionTreeClassifier()
cross_val2=cross_val_score(regressor, x, y, cv=10, scoring ='accuracy')
cross_val2

array([0.85365854, 0.75609756, 0.87804878, 0.825     , 0.875     ,
       0.85      , 0.775     , 0.76923077, 0.74358974, 0.82051282])

In [0]:
cross_val2.mean()

0.8146138211382115

In [0]:
cross_val2.std()

0.047631161595748206